before_script:
  # install XSpec
  - git clone -b master https://github.com/xspec/xspec.git /tmp/xspec
  # install Saxon
  - mkdir -p /tmp/xspec/saxon/
  - export SAXON_CP=/tmp/xspec/saxon/saxon9he.jar
  - wget https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12.jar -U "Any User Agent" -O ${SAXON_CP} 

script:
  - cd Xspec-Travis/fhir_2_ada/mp/9.0.7/beschikbaarstellen_medicatiegegevens/payload/test
  - echo "execute XSpec unit tests"
  - bash run-xspec-tests.sh